# Generated by Django 4.2.2 on 2023-11-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('wf_box_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('purchased', 'Purchased'), ('in_transit', 'In Transit'), ('in_transit_with_wfbox', 'In Transit with WfBox'), ('na', 'N/A')], default='na', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
