# Generated by Django 4.2.2 on 2023-11-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_request_weight_request_wf_box_received_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='items',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='provider',
            field=models.CharField(choices=[('ebay', 'Ebay'), ('tecnoplay', 'Tecnoplay'), ('aliexpress', 'AliExpress'), ('cliente', 'Cliente'), ('otros', 'Otros')], default='ebay', max_length=100),
        ),
    ]
