# Generated by Django 4.2.2 on 2023-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
