# Generated by Django 4.2.2 on 2023-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_request_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('percentage', 'Percentage %'), ('fixed', 'Fixed')], default='percentage', max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
