# Generated by Django 4.2.2 on 2023-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uses',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
