# Generated by Django 4.2.2 on 2023-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_coupon_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
