# Generated by Django 4.2.2 on 2024-02-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
