# Generated by Django 4.2.2 on 2024-03-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='details',
            field=models.CharField(blank=True, help_text='Por ejemplo: Primer Gabeta', max_length=200, null=True),
        ),
    ]
