# Generated by Django 4.2.2 on 2025-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_location_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_online_purchase', models.BooleanField(default=False)),
            ],
        ),
    ]
