# Generated by Django 4.2.2 on 2025-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_create_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='uses',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
