# Generated by Django 4.2.1 on 2023-06-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoGames',
            new_name='VideoGame',
        ),
        migrations.RenameField(
            model_name='collectable',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='collectable',
            old_name='descripcion',
            new_name='description',
        ),
    ]
