# Generated by Django 4.2.2 on 2023-06-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_videogames_videogame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='provider_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='departure_date',
            new_name='provider_purchase_date',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(choices=[('joseph', 'Joseph'), ('mauricio', 'Mauricio'), ('business', 'Business')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='console',
            name='console',
            field=models.CharField(choices=[('ps1', 'PS1'), ('ps2', 'PS2'), ('ps3', 'PS3'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('n64', 'N64'), ('snes', 'SNES'), ('switch', 'Nintendo Switch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='console',
            field=models.CharField(choices=[('ps1', 'PlayStation1'), ('ps2', 'PlayStation2'), ('ps3', 'PlayStation3'), ('ps4', 'PlayStation4'), ('ps5', 'PlayStation5'), ('n64', 'N64'), ('snes', 'Snes'), ('switch', 'Switch')], max_length=20),
        ),
    ]
