# Generated by Django 4.2.2 on 2023-06-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_price_product_provider_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('jp', 'Japan'), ('usa', 'USA'), ('eu', 'Europe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, help_text='En colones', max_digits=8),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='console',
            field=models.CharField(choices=[('ps1', 'PS1'), ('ps2', 'PS2'), ('ps3', 'PS3'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('n64', 'N64'), ('snes', 'SNES'), ('switch', 'Nintendo Switch')], max_length=20),
        ),
    ]
