# Generated by Django 4.2.2 on 2023-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_collectable_description_collectable_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
