# Generated by Django 4.2.2 on 2023-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_accessory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(blank=True, choices=[('joseph', 'Joseph'), ('mauricio', 'Mauricio'), ('business', 'Business')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, choices=[('jp', 'Japan'), ('usa', 'USA'), ('eu', 'Europe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
