# Generated by Django 4.2.2 on 2023-06-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_accessory_console_alter_console_console_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='console',
            old_name='console',
            new_name='title',
        ),
    ]
