# Generated by Django 4.2.2 on 2023-06-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
