# Generated by Django 4.2.2 on 2023-08-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('sold', 'Vendido'), ('availabel', 'Disponible'), ('reserved', 'Apartado'), ('na', 'N/A')], default='availabel', max_length=100),
        ),
    ]
