# Generated by Django 4.2.2 on 2023-08-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_report_sale'),
        ('product', '0024_alter_product_state'),
    ]

    operations = [
    ]
