# Generated by Django 4.2.2 on 2023-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_configure_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('sold', 'Vendido'), ('available', 'Disponible'), ('reserved', 'Apartado'), ('na', 'N/A')], default='available', max_length=100),
        ),
    ]
