# Generated by Django 4.2.2 on 2023-08-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_fix_sold_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='En colones', max_digits=8, null=True),
        ),
    ]
