# Generated by Django 4.2.2 on 2023-08-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='type',
        ),
    ]
