# Generated by Django 4.2.2 on 2023-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('status_text', models.TextField()),
                ('response', models.TextField()),
                ('request', models.TextField()),
                ('ipv4_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=100)),
                ('is_ajax', models.BooleanField()),
                ('is_secure', models.BooleanField()),
            ],
        ),
    ]
