# Generated by Django 4.2.2 on 2023-08-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_log_is_ajax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='warranty_type',
            field=models.CharField(max_length=100),
        ),
    ]
