# Generated by Django 4.2.2 on 2023-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_sale_payment_method_alter_sale_warranty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
