# Generated by Django 4.2.2 on 2023-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
