# Generated by Django 4.2.2 on 2023-10-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_order'),
        ('product', '0039_product_provider_alter_accessory_console_and_more'),
    ]

    operations = [
    ]
