# Generated by Django 4.2.2 on 2023-10-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_merge_20231023_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
