# Generated by Django 4.2.2 on 2023-11-13 02:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#00FF00', image_field=None, max_length=25, samples=None),
        ),
    ]
