# Generated by Django 4.2.2 on 2023-12-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_sale_total_net'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='gross_total',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_net',
            new_name='net_total',
        ),
    ]
