# Generated by Django 4.2.2 on 2023-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_product_notes_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas', null=True),
        ),
    ]
