# Generated by Django 4.2.2 on 2023-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_rename_total_sale_gross_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
