# Generated by Django 4.2.2 on 2023-12-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_product_notes'),
        ('product', '0050_payment_net_price'),
    ]

    operations = [
    ]
