# Generated by Django 4.2.2 on 2023-12-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_merge_0049_alter_product_notes_0050_payment_net_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Descripción que puede ver el cliente'),
        ),
    ]
