# Generated by Django 4.2.2 on 2024-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('repair', 'Repair'), ('request', 'Request'), ('reserve', 'Reserve'), ('purchase', 'Purchase')], default='purchase', max_length=100),
        ),
    ]
