# Generated by Django 4.2.2 on 2024-01-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_product_amount_to_notify_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
