# Generated by Django 4.2.2 on 2024-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_report_total_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_business',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='En colones', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_joseph',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='En colones', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_mauricio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='En colones', max_digits=8, null=True),
        ),
    ]
