# Generated by Django 4.2.2 on 2024-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_product_provider_price_alter_product_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='platform',
            field=models.CharField(choices=[('store', 'Store'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('event', 'Event'), ('other', 'Other')], default='store', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping',
            field=models.BooleanField(default=False, help_text='Si es por envio'),
        ),
    ]
