# Generated by Django 4.2.2 on 2024-02-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Used mainly to hide duplicate products'),
        ),
    ]
