# Generated by Django 4.2.2 on 2024-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_alter_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='internal',
            field=models.BooleanField(default=False, help_text='Si es interno, entonces solo se muestra en la paginaadministrativa, en la pagina web no ni el excel por ejemplo'),
        ),
    ]
