# Generated by Django 4.2.2 on 2024-03-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_tag_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sent',
            field=models.BooleanField(default=False, help_text='Si ya se envio'),
        ),
    ]
