# Generated by Django 4.2.2 on 2024-03-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('videogame', 'Videojuego'), ('console', 'Consola'), ('accessory', 'Accesorio'), ('collectable', 'Collecionable')], default='videogame', max_length=100),
        ),
    ]
