# Generated by Django 4.2.2 on 2024-03-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_product_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['title'], name='product_acc_title_7f97fa_idx'),
        ),
        migrations.AddIndex(
            model_name='collectable',
            index=models.Index(fields=['title'], name='product_col_title_f411c1_idx'),
        ),
        migrations.AddIndex(
            model_name='collectable',
            index=models.Index(fields=['category'], name='product_col_categor_787b11_idx'),
        ),
        migrations.AddIndex(
            model_name='console',
            index=models.Index(fields=['title'], name='product_con_title_806ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_pro_barcode_31e7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['used'], name='product_pro_used_885cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['state'], name='product_pro_state_1fc0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hidden'], name='product_pro_hidden_c20f58_idx'),
        ),
        migrations.AddIndex(
            model_name='videogame',
            index=models.Index(fields=['title'], name='product_vid_title_baf4d3_idx'),
        ),
    ]
