# Generated by Django 4.2.2 on 2024-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_accessory_product_acc_title_7f97fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payments_completed',
            field=models.BooleanField(default=True, help_text='Si ya termino de pagar el producto'),
        ),
    ]
