# Generated by Django 4.2.2 on 2024-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_alter_accessory_console_alter_console_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(blank=True, choices=[('joseph', 'Joseph'), ('mauricio', 'Mauricio'), ('business', 'Business'), ('consignacion', 'Consignacion')], default='business', max_length=100, null=True),
        ),
    ]
