# Generated by Django 4.2.2 on 2025-02-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_alter_accessory_console_alter_console_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('sold', 'Vendido'), ('available', 'Disponible'), ('reserved', 'Apartado'), ('pending', 'Pago Pendiente'), ('na', 'N/A')], default='available', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='platform',
            field=models.CharField(choices=[('store', 'Store'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('event', 'Event'), ('online', 'Online'), ('other', 'Other')], default='store', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('repair', 'Repair'), ('request', 'Request'), ('reserve', 'Reserve'), ('purchase', 'Purchase'), ('pending', 'Pending')], default='purchase', max_length=100),
        ),
    ]
