# Generated by Django 4.2.2 on 2025-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_sale_onvo_pay_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_consignment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='En colones', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('repair', 'Repair'), ('request', 'Request'), ('reserve', 'Reserve'), ('purchase', 'Purchase'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='purchase', max_length=100),
        ),
    ]
