# Generated by Django 4.2.2 on 2025-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_report_total_consignment_alter_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('videogame', 'Videojuego'), ('console', 'Consola'), ('accessory', 'Accesorio'), ('replacement', 'Replacement'), ('collectable', 'Collecionable'), ('food', 'Comida')], default='videogame', max_length=100),
        ),
    ]
