# Generated by Django 4.2.2 on 2025-03-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0083_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mainDish', 'Plato Principal')], max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='possimplifi_categor_d9cfd7_idx'), models.Index(fields=['title'], name='possimplifi_title_1171ff_idx')],
            },
        ),
    ]
