# Generated by Django 4.2.2 on 2025-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possimplified', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('mainDish', 'Plato Principal')], default='mainDish', max_length=100),
        ),
    ]
